print("**AN EASY HOMMADE PIZZA RECIPE**")
print(" ") 
print("Ingredients")
print("Cornmeal for baking sheet")
print("Flour for surface")
print("Pizza dough")
print("3/4c marinara sauce")
print("Mozzarella cheese")
print("2tbsp. grated parmesan")
print("Basil for sprinkling")
print(" ")
print("DIRECTION")
print("Start with a solid pizza dough recipe")
print("Make the dough")
print("Proof the dough")
print("Prepare the sauce and toppings")
print("Shape the dough")
print("Bake the pizza")
print("Cool the pizza and serve with chilled drink")
